### ISSUE TITLE
Feature Requests - Context Menu, Icon, Notification

### ISSUE THREAD

**Issue by mortyobnoxious** [ketankr9/cloud-torrent-extension#1]
Hi, thank you so much for this great extension. 

I would like to suggest a few improvements:
1. I think it should work only when a URL is right-clicked. It shouldn't be always visible on context menu.
2. If you're considering to change icon, I suggest using this: http://fa2png.io/r/font-awesome/magnet/?color=8798a5&margin=0&size=64
3. You've already stated this but I would like to add anyway, a simple notification would be great.

**Comment by ketankr9** [comment]
For implementing notification on adding request from torrent-server I am getting the following error:
```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://10.2.60.12:3000/api/magnet. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).```  

The [XHR](https://github.com/ketankr9/cloud-torrent-extension/blob/master/magnet-extension/background.js#L27) request is successfully sent to the torrent server, but its response is being rejected, hence we cannot determine if the torrent server did successfully receive the magnet or it was lost midway.  

I don't have much knowledge regarding **Cross-Origin Request**, someone can help.

**Comment by ketankr9** [comment]
@mortyobnoxious Please download the patched [simple-torrent binary v1.2.1](http://s000.tinyupload.com/index.php?file_id=89235351238068471330) for the notification feature to work successfully, until and unless my pull request gets committed in the central repository.  

This will work even if the HTTP authentication is enabled from the server side.  

![Screenshot](https://github.com/ketankr9/cloud-torrent-extension/raw/master/screenshot_notification2.png)
Please let me know if this works for you.

**Comment by mortyobnoxious** [comment]
I really like to try that but I don't know how can i install it on google cloud. I have to wait for your pull requests to be included, I guess.
