### ISSUE TITLE
Feature Request - Adding URLs

### ISSUE THREAD

**Issue by mortyobnoxious** [ketankr9/cloud-torrent-extension#2]
Hi, again :)

I know I've been asking a lot.

You use magnet API: `http://'+serverip+'/api/magnet`

but there's also an API for URLs `http://'+serverip+'/api/url`

Support for this would be great.

**Comment by ketankr9** [comment]
>I know I've been asking a lot.   

@mortyobnoxious I am glad that you are asking.  

>but there's also an API for URLs http://'+serverip+'/api/url  

Can you post an url (as an example) so that I can test it, since most of the torrents are available as magnet.

**Comment by mortyobnoxious** [comment]
yts has it:
https://yts.lt/torrent/download/blablablabla

**Comment by mortyobnoxious** [comment]
Thank you.
