### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [ketankr9/cloud-torrent-extension#3]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by ketankr9** [comment]
Hi @codehangen , thanks for showing interest.

I created this extension to solve my use case, nowadays I am not very active on torrent and have stopped using this extension.

If you are interested in this project, feel free to create your own fork, because I won't be active here.

**Comment by ghost** [comment]
Hi ketankr9.

> Hi @codehangen , thanks for showing interest.
> I created this extension to solve my use case, nowadays I am not very active on torrent and have stopped using this extension.
> If you are interested in this project, feel free to create your own fork, because I won't be active here.

thank you for feedback. I'll fork today, and thanks for the info, have a great day. 

*I'm going to close this question since I answered my question.*
